# .travis.yml Execution script for role tests on Travis-CI
---
sudo: required

env:
  global:
    - ANSIBLE_VERSION=2.5
  matrix:
    - DISTRIBUTION: centos
      VERSION: 7
    - DISTRIBUTION: ubuntu
      VERSION: 16.04
    - DISTRIBUTION: ubuntu
      VERSION: 18.04
#    - DISTRIBUTION: debian
#      VERSION: 9

services:
  - docker

before_install:
  # Install latest Git
  - sudo apt-get update
  - sudo apt-get install --only-upgrade git
  # Lint
  - sudo pip install --upgrade pip
  - sudo pip install ansible-lint yamllint

script:
  # Lint
  # - ansible-lint . -x ANSIBLE0016,ANSIBLE0503
  - yamllint .

  # Create container and apply test playbook
  - ./docker-tests/docker-tests.sh

  # Run functional tests on the container
  - SUT_ID=$(docker ps -qa) ./docker-tests/functional-tests.sh
  #- SUT_IP=172.17.0.2 ./docker-tests/functional-tests.sh
...
